### ISSUE TITLE
Download issues with the 2023-nr-clustering sqlite file

### ISSUE THREAD

**Issue by Mohammed-Quraishi** [Arcadia-Science/prehgt#57]
Hello preHGT developers,

I am currently unable to fully download the nr_cluster_taxid_formatted_final.sqlite file from https://osf.io/5qj7e/download (all the other databases downloaded perfectly). Every time I try to download it, Regardless of if use a CLI or Chrome to download it, it always fails at 54.89 GB, and when using chrome I get the "Failed - Network Error" message. I have ensured that I have enough storage to download the file, and have tried to troubleshoot the issue by using different networks, browsers, as well as the nohup command. I have tried to use a download manager, but that too fails at 54.89 and reports that the "direct download link invalid". 

Could you advise me on how to solve this issue?

Thank you,
Mohammed Quraishi

**Comment by taylorreiter** [comment]
Hi @Mohammed-Quraishi, I can't think of any reasons why that would be happening. Here is the direct link in google drive, can you try and download it from here instead? https://drive.google.com/file/d/1Fa09Qq5S47e3Rxxd4hz3rw0XHklK6ezr/view?usp=drive_link

**Comment by Mohammed-Quraishi** [comment]
Hello @taylorreiter,

Thank you for responding so quickly! The new link still failed at around 50 GB; however, I was able to seamlessly resume the download using Google Chrome without it restarting from the very beginning. I hypothesize that the issue may lie within downloading from Google Drive itself, though it seems to be resolvable if the direct download link is being used. I apologize for not being able to provide more information on the issue and how to recreate it, but I hope this helps.

Mohammed Quraishi

**Comment by taylorreiter** [comment]
Thank you! I'm glad you were able to get the file and I'm sorry it caused you so much trouble!
